import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import AppProvider from "../components/AppProvider";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AppProvider>
        <NavBar/>
        {children}
        </AppProvider>
      
      </body>
    </html>
  );
}
